name: h1d023030_tugas6
description: "com.khailasalsa"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0' # Versi yang lebih baik

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0 # <-- BARIS INI DITAMBAHKAN DI SINI

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
